/**
 * AUTO-GENERATED BY CONTROLDECK
 * DO NOT EDIT MANUALLY
 */
module.exports = {
  apps: [
  {
    "name": "test-ser1",
    "cwd": "/home/meow/bow",
    "script": "serve",
    "env": {},
    "exec_mode": "fork",
    "watch": false,
    "autorestart": true
  },
  {
    "name": "test-2",
    "cwd": "/home/meow/bow",
    "script": "serve",
    "env": {},
    "exec_mode": "fork",
    "watch": false,
    "autorestart": true
  }
]
};
