import fs from "fs";
import path from "path";

export function ensureEcosystemFile(ecosystemPath: string) {
  const dir = path.dirname(ecosystemPath);

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  if (!fs.existsSync(ecosystemPath)) {
    const content = `/**
 * AUTO-GENERATED BY CONTROLDECK
 * DO NOT EDIT MANUALLY
 */
module.exports = {
  apps: []
};
`;
    fs.writeFileSync(ecosystemPath, content);
  }
}
