import fs from "fs";
import { connectDB } from "@/lib/mongodb";
import Service from "@/models/service";

export async function generateEcosystem(ecosystemPath: string) {
  await connectDB();

  const services = await Service.find({ enabled: true });

  const apps = services.map((s) => ({
    name: s.name,
    cwd: s.cwd,
    script: s.script,
    args: s.args,
    interpreter: s.interpreter,
    env: Object.fromEntries(s.env || []),
    exec_mode: s.exec_mode || "fork",
    watch: s.watch ?? false,
    autorestart: s.autorestart ?? true,
  }));

  const content = `/**
 * AUTO-GENERATED BY CONTROLDECK
 * DO NOT EDIT MANUALLY
 */
module.exports = {
  apps: ${JSON.stringify(apps, null, 2)}
};
`;

  fs.writeFileSync(ecosystemPath, content);
}
